import type { Atelier, Utilisateur } from '../types'

export const mockUtilisateur: Utilisateur = {
  id: 'user-1',
  nom: 'Jean Dupont',
  email: 'jean.dupont@example.com',
  avatar: 'JD',
  role: 'learner',
  ateliersInscrits: ['workshop-1', 'workshop-2'],
}

export const mockAteliers: Atelier[] = [
  {
    id: 'workshop-1',
    titre: 'Introduction à React',
    description: 'Découvrez les bases de React et commencez à créer des interfaces dynamiques.',
    date: '2026-01-20',
    heure: '14:00',
    duree: 120,
    niveau: 'beginner',
    categorie: 'Frontend',
    instructeur: { nom: 'Sophie Martin', avatar: 'SM' },
    nomImage: 'react',
    maxParticipants: 30,
    currentParticipants: 28,
    estInscrit: true,
    statut: 'upcoming',
    tags: ['React', 'JavaScript', 'Frontend'],
  },
  {
    id: 'workshop-2',
    titre: 'TypeScript Avancé',
    description: 'Maîtrisez les types avancés et les génériques en TypeScript.',
    date: '2026-01-22',
    heure: '10:00',
    duree: 150,
    niveau: 'advanced',
    categorie: 'Backend',
    instructeur: { nom: 'Marc Dubois', avatar: 'MD' },
    nomImage: 'typescript',
    maxParticipants: 20,
    currentParticipants: 18,
    estInscrit: true,
    statut: 'upcoming',
    tags: ['TypeScript', 'JavaScript', 'Backend'],
  },
  {
    id: 'workshop-3',
    titre: 'CSS Responsive Design',
    description: 'Apprenez à créer des sites web responsifs avec les meilleures pratiques CSS.',
    date: '2026-01-25',
    heure: '15:30',
    duree: 90,
    niveau: 'beginner',
    categorie: 'Frontend',
    instructeur: { nom: 'Amélie Bernard', avatar: 'AB' },
    nomImage: 'css',
    maxParticipants: 35,
    currentParticipants: 32,
    estInscrit: false,
    statut: 'upcoming',
    tags: ['CSS', 'Responsive', 'Frontend'],
  },
  {
    id: 'workshop-4',
    titre: 'Node.js et Express',
    description: 'Créez des serveurs web performants avec Node.js et Express.',
    date: '2026-01-28',
    heure: '09:00',
    duree: 180,
    niveau: 'intermediate',
    categorie: 'Backend',
    instructeur: { nom: 'Pierre Laurent', avatar: 'PL' },
    nomImage: 'node',
    maxParticipants: 25,
    currentParticipants: 20,
    estInscrit: false,
    statut: 'upcoming',
    tags: ['Node.js', 'Express', 'Backend'],
  },
  {
    id: 'workshop-5',
    titre: 'Bases de données SQL',
    description: 'Maîtrisez les requêtes SQL et la conception de bases de données.',
    date: '2026-02-01',
    heure: '13:00',
    duree: 120,
    niveau: 'beginner',
    categorie: 'Database',
    instructeur: { nom: 'Nathalie Girard', avatar: 'NG' },
    nomImage: 'sql',
    maxParticipants: 28,
    currentParticipants: 25,
    estInscrit: false,
    statut: 'upcoming',
    tags: ['SQL', 'Database', 'Backend'],
  },
  {
    id: 'workshop-6',
    titre: 'Git et GitHub',
    description: 'Apprenez le contrôle de version avec Git et collaborez efficacement sur GitHub.',
    date: '2026-01-18',
    heure: '11:00',
    duree: 90,
    niveau: 'beginner',
    categorie: 'DevTools',
    instructeur: { nom: 'Claude Moreau', avatar: 'CM' },
    nomImage: 'git',
    maxParticipants: 40,
    currentParticipants: 35,
    estInscrit: false,
    statut: 'ongoing',
    tags: ['Git', 'GitHub', 'DevTools'],
  },
]

export const mockInstructeurAteliers: Atelier[] = [
  {
    id: 'trainer-workshop-1',
    titre: 'React Avancé pour Formateurs',
    description: 'Concevez des ateliers React interactifs et optimisés pour vos apprenants.',
    date: '2026-02-05',
    heure: '09:30',
    duree: 180,
    niveau: 'advanced',
    categorie: 'Frontend',
    instructeur: { nom: 'Sophie Martin', avatar: 'SM' },
    nomImage: 'react',
    maxParticipants: 24,
    currentParticipants: 18,
    statut: 'upcoming',
    tags: ['React', 'Animation', 'UX'],
  },
  {
    id: 'trainer-workshop-2',
    titre: 'Design Systems et Accessibilité',
    description: 'Structurez vos composants UI avec une approche design system inclusive.',
    date: '2026-01-30',
    heure: '14:00',
    duree: 150,
    niveau: 'intermediate',
    categorie: 'Frontend',
    instructeur: { nom: 'Sophie Martin', avatar: 'SM' },
    nomImage: 'css',
    maxParticipants: 20,
    currentParticipants: 20,
    statut: 'ongoing',
    tags: ['Design', 'A11y', 'CSS'],
  },
  {
    id: 'trainer-workshop-3',
    titre: 'Architecture API avec TypeScript',
    description: 'Organisez vos API pour des projets pédagogiques évolutifs.',
    date: '2025-12-18',
    heure: '10:00',
    duree: 120,
    niveau: 'advanced',
    categorie: 'Backend',
    instructeur: { nom: 'Sophie Martin', avatar: 'SM' },
    nomImage: 'typescript',
    maxParticipants: 18,
    currentParticipants: 16,
    statut: 'completed',
    tags: ['TypeScript', 'API', 'Backend'],
  },
]

export const categoriesDisponibles: string[] = [
  'Frontend',
  'Backend',
  'Database',
  'DevTools',
]

export const niveauxDisponibles: { valeur: string; etiquette: string }[] = [
  { valeur: 'beginner', etiquette: 'Débutant' },
  { valeur: 'intermediate', etiquette: 'Intermédiaire' },
  { valeur: 'advanced', etiquette: 'Avancé' },
]
