export const mockUtilisateur = {
  id: 'user-1',
  name: 'Jean Dupont',
  email: 'jean.dupont@example.com',
  avatar: 'JD',
  role: 'learner',
  enrolledWorkshops: ['workshop-1', 'workshop-2'],
}

export const mockAteliers = [
  {
    id: 'workshop-1',
    title: 'Introduction à React',
    description: 'Découvrez les bases de React et commencez à créer des interfaces dynamiques.',
    date: '20/01/2026',
    time: '14:00',
    duration: 120,
    level: 'beginner',
    category: 'Frontend',
    instructor: { name: 'Sophie Martin', initiales: 'SM' },
    couleurImage: 'img-react',
    nomImage: 'React Workshop',
    maxParticipants: 30,
    currentParticipants: 28,
    isEnrolled: true,
    status: 'upcoming',
    tags: ['React', 'JavaScript', 'Frontend'],
  },
  {
    id: 'workshop-2',
    title: 'TypeScript Avancé',
    description: 'Maîtrisez les types avancés et les génériques en TypeScript.',
    date: '22/01/2026',
    time: '10:00',
    duration: 150,
    level: 'advanced',
    category: 'Backend',
    instructor: { name: 'Marc Dubois', initiales: 'MD' },
    couleurImage: 'img-typescript',
    nomImage: 'TypeScript Workshop',
    maxParticipants: 20,
    currentParticipants: 18,
    isEnrolled: true,
    status: 'upcoming',
    tags: ['TypeScript', 'JavaScript', 'Backend'],
  },
  {
    id: 'workshop-3',
    title: 'CSS Responsive Design',
    description: 'Apprenez à créer des sites web responsifs avec les meilleures pratiques CSS.',
    date: '25/01/2026',
    time: '15:30',
    duration: 90,
    level: 'beginner',
    category: 'Frontend',
    instructor: { name: 'Amélie Bernard', initiales: 'AB' },
    couleurImage: 'img-css',
    nomImage: 'CSS Workshop',
    maxParticipants: 35,
    currentParticipants: 32,
    isEnrolled: false,
    status: 'upcoming',
    tags: ['CSS', 'Responsive', 'Frontend'],
  },
  {
    id: 'workshop-4',
    title: 'Node.js et Express',
    description: 'Créez des serveurs web performants avec Node.js et Express.',
    date: '28/01/2026',
    time: '09:00',
    duration: 180,
    level: 'intermediate',
    category: 'Backend',
    instructor: { name: 'Pierre Laurent', initiales: 'PL' },
    couleurImage: 'img-node',
    nomImage: 'Node.js Workshop',
    maxParticipants: 25,
    currentParticipants: 20,
    isEnrolled: false,
    status: 'upcoming',
    tags: ['Node.js', 'Express', 'Backend'],
  },
  {
    id: 'workshop-5',
    title: 'Bases de données SQL',
    description: 'Maîtrisez les requêtes SQL et la conception de bases de données.',
    date: '01/02/2026',
    time: '13:00',
    duration: 120,
    level: 'beginner',
    category: 'Database',
    instructor: { name: 'Nathalie Girard', initiales: 'NG' },
    couleurImage: 'img-sql',
    nomImage: 'SQL Workshop',
    maxParticipants: 28,
    currentParticipants: 25,
    isEnrolled: false,
    status: 'upcoming',
    tags: ['SQL', 'Database', 'Backend'],
  },
  {
    id: 'workshop-6',
    title: 'Git et GitHub',
    description: 'Apprenez le contrôle de version avec Git et collaborez efficacement sur GitHub.',
    date: '18/01/2026',
    time: '11:00',
    duration: 90,
    level: 'beginner',
    category: 'DevTools',
    instructor: { name: 'Claude Moreau', initiales: 'CM' },
    couleurImage: 'img-git',
    nomImage: 'Git Workshop',
    maxParticipants: 40,
    currentParticipants: 35,
    isEnrolled: false,
    status: 'ongoing',
    tags: ['Git', 'GitHub', 'DevTools'],
  },
]

export const categoriesDisponibles = [
  'Frontend', 'Backend', 'Database', 'DevTools'
]

export const niveauxDisponibles = [
  { valeur: 'beginner', libelle: 'Débutant' },
  { valeur: 'intermediate', libelle: 'Intermédiaire' },
  { valeur: 'advanced', libelle: 'Avancé' },
]

export const mockInstructeurAteliers = [
  {
    id: 'trainer-workshop-1',
    titre: 'React Avancé pour Formateurs',
    description: 'Concevez des ateliers React interactifs et optimisés pour vos apprenants.',
    date: '2026-02-05',
    heure: '09:30',
    duree: 180,
    niveau: 'advanced',
    categorie: 'Frontend',
    instructeur: { nom: 'Sophie Martin', avatar: '/images/avatars/sm.svg' },
    nomImage: 'react',
    maxParticipants: 24,
    currentParticipants: 18,
    statut: 'upcoming',
    tags: ['React', 'Animation', 'UX'],
  },
  {
    id: 'trainer-workshop-2',
    titre: 'Design Systems et Accessibilité',
    description: 'Structurez vos composants UI avec une approche design system inclusive.',
    date: '2026-01-30',
    heure: '14:00',
    duree: 150,
    niveau: 'intermediate',
    categorie: 'Frontend',
    instructeur: { nom: 'Sophie Martin', avatar: '/images/avatars/sm.svg' },
    nomImage: 'css',
    maxParticipants: 20,
    currentParticipants: 20,
    statut: 'ongoing',
    tags: ['Design', 'A11y', 'CSS'],
  },
  {
    id: 'trainer-workshop-3',
    titre: 'Architecture API avec TypeScript',
    description: 'Organisez vos API pour des projets pédagogiques évolutifs.',
    date: '2025-12-18',
    heure: '10:00',
    duree: 120,
    niveau: 'advanced',
    categorie: 'Backend',
    instructeur: { nom: 'Sophie Martin', avatar: '/images/avatars/sm.svg' },
    nomImage: 'typescript',
    maxParticipants: 18,
    currentParticipants: 16,
    statut: 'completed',
    tags: ['TypeScript', 'API', 'Backend'],
  },
]
